stages:
  - build

image: docker:20

services:
  - docker:dind

dockerize:
  stage: build
  tags: [docker]
  variables:
    IMAGE_NAME: zoidenberg/gate-up:$CI_COMMIT_TAG
  before_script:
    - mkdir $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME
  only:
    - tags
