version: "2"

services:
  nodeexporter:
    image: prom/node-exporter:v1.3.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    scale: 1
    expose:
      - 9100
    labels:
      - "com.github.nmix.gate-up.scrape"
    environment:
      SCRAPE_PORT: 9100
      # SCRAPE_PATH: "/metrics"

  httpie:
    image: alpine/httpie:latest
    container_name: httpie
    entrypoint: ["sleep", "9999999"]

  app:
    image: gate-up
    container_name: app
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./:/app
    command:
      - "sleep"
      - "9999999"

  # busybox:
  #   image: busybox
  #   container_name: busybox
  #   command:
  #     - 'sleep'
  #     - '3600'
